apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-clone

spec:
  replicas: 2

  selector:
    matchLabels:
      app: amazon-clone

  template:
    metadata:
      labels:
        app: amazon-clone

    spec:
      containers:
      - name: amazon-clone
        image: amazon-clone
        imagePullPolicy: Never

        ports:
        - containerPort: 80
